data:extend({
--RECIPE
{--Workshop Locomotive
	type = "recipe",
	name = "workshop-loco-r1",
	enabled = false,
	ingredients = {
		{"reinforced-iron-plate-r1", 5},
		{"reinforced-copper-plate-r1", 5},
		{"electric-component-r1", 10},
		{"cable-r1", 10},
		{"half-assembler-r1", 2}
	},
	result = "workshop-loco-r1"
},
{--Workshop Wagon
	type = "recipe",
	name = "workshop-wagon-r1",
	enabled = false,
	ingredients = {
		{"reinforced-iron-plate-r1", 5},
		{"reinforced-copper-plate-r1", 5},
		{"electric-component-r1", 10},
		{"cable-r1", 10},
		{"assembler-r1", 2}
	},
	result = "workshop-wagon-r1"
},
{--Workshop Extreme Fuel
	type = "recipe",
	name = "workshop-giga-r1",
	enabled = false,
	ingredients = {
		{"reinforced-coal-plate-r1", 20},
		{"electric-component-r1", 10},
		{"cable-r1", 10},
		{"assembler-r1", 2}
	},
	result = "workshop-giga-r1"
},
--ITEM
{--Workshop Locomotive
	type = "item",
	name = "workshop-loco-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-loco.png",
	icon_size = 32,
	subgroup = "re-workshop",
	order = "a-b",
	place_result = "workshop-loco-r1",
	stack_size = 50,
},
{--Workshop Wagon
	type = "item",
	name = "workshop-wagon-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-wagon.png",
	icon_size = 32,
	subgroup = "re-workshop",
	order = "a-c",
	place_result = "workshop-wagon-r1",
	stack_size = 50,
},
{--Workshop Extreme Fuel
	type = "item",
	name = "workshop-giga-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-giga-fuel.png",
	icon_size = 32,
	subgroup = "re-workshop",
	order = "a-d",
	place_result = "workshop-giga-r1",
	stack_size = 50,
},
--ENTITY
{--Workshop Locomotive
	type = "assembling-machine",
	name = "workshop-loco-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-loco.png",
	icon_size = 32,
	flags = {"placeable-neutral","placeable-player", "player-creation"},
	minable = {hardness = 0.2, mining_time = 0.5, result = "workshop-loco-r1"},
	max_health = 750,
	corpse = "big-remnants",
	resistances = {{type = "physical",percent = 60},},
	collision_box = {{-2.7, -2.7}, {2.7, 2.7}},
	selection_box = {{-3.0, -3.0}, {3.0, 3.0}},
	animation = {			
		filename = "__RERailworld__/graphics/entity/machinery/workshop-loco.png",
		width = 224,
		height = 224,
		shift = {0.5, -0.375},
		frame_count = 1,
		line_length = 1,			
	},		
	crafting_categories = {"red-workshop-locomotive"},
	energy_usage = "1MW",
	ingredient_count = 6,
	crafting_speed = 0.5,
	energy_source = {
		type = "electric",
		input_priority = "secondary",
		usage_priority = "secondary-input",
		emissions = 0.04,
	},
	module_specification = {
		module_slots = 1,			
	},
	allowed_effects = {"consumption", "speed", "productivity", "pollution"},		
	order="a-b",
	subgroup = "re-workshop",
},
{--Workshop Wagon
	type = "assembling-machine",
	name = "workshop-wagon-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-wagon.png",
	icon_size = 32,
	flags = {"placeable-neutral","placeable-player", "player-creation"},
	minable = {hardness = 0.2, mining_time = 0.5, result = "workshop-wagon-r1"},
	max_health = 750,
	corpse = "big-remnants",
	resistances = {{type = "physical",percent = 60},},
	collision_box = {{-2.7, -2.7}, {2.7, 2.7}},
	selection_box = {{-3.0, -3.0}, {3.0, 3.0}},
	animation = {			
		filename = "__RERailworld__/graphics/entity/machinery/workshop-wagon.png",
		width = 224,
		height = 224,
		shift = {0.5, -0.375},
		frame_count = 4,
		line_length = 4,			
		animation_speed = 0.25
	},		
	crafting_categories = {"red-workshop-wagon"},
	energy_usage = "1MW",
	ingredient_count = 6,
	crafting_speed = 0.5,
	energy_source = {
		type = "electric",
		input_priority = "secondary",
		usage_priority = "secondary-input",
		emissions = 0.04,
	},			
	module_specification = {
		module_slots = 1,			
	},
	allowed_effects = {"consumption", "speed", "productivity", "pollution"},		
	order="a-c",
	subgroup = "re-workshop",
},
{--Workshop Extreme Fuel
	type = "assembling-machine",
	name = "workshop-giga-r1",
	icon = "__RERailworld__/graphics/icons/machinery/workshop-giga-fuel.png",
	icon_size = 32,
	flags = {"placeable-neutral","placeable-player", "player-creation"},
	minable = {hardness = 0.2, mining_time = 0.5, result = "workshop-giga-r1"},
	max_health = 500,
	corpse = "big-remnants",
	resistances = {{type = "physical",percent = 60},},
	collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
	selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
	fast_replaceable_group = "assembling-machine",
	animation = {			
		filename = "__RERailworld__/graphics/entity/machinery/workshop-giga-fuel.png",
		width = 128,
		height = 128,
		shift = {0.5, -0.5},
		frame_count = 16,
		line_length = 4,			
		animation_speed = 1,
	},		
	crafting_categories = {"red-extreme-fuel"},
	energy_usage = "600kW",
	ingredient_count = 4,
	crafting_speed = 1,
	energy_source = {
		type = "electric",
		input_priority = "secondary",
		usage_priority = "secondary-input",
		emissions = 0.04,
	},			
	module_specification = {
		module_slots = 1,			
	},
	allowed_effects = {"consumption", "speed", "productivity", "pollution"},		
	order="a-d",
	subgroup = "re-workshop",
},
})